### ISSUE TITLE
Add Page Title fails with invalid HTML in head element

### ISSUE THREAD

**Issue by adamfortuna** [pluralsight-projects/HelloPluralsightProject#4]
If the `head` of the document isn't valid, the first task will fail with a message that you didn't add a title tag. It should instead either pass, or fail with a message mentioning that your `head` isn't valid HTML.

```
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    asdfsafa
    <title>asdfas</title>
  </head>
   <body>
  </body>
</html>

```

**Comment by Raveendra7** [comment]
Use below code for first task.

<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>asdfas</title>
  </head>
   <body>
  </body>
</html>
